#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET="$HOME/.local/share/yakushi-control-deck"; BIN="$HOME/.local/bin"; DATA="$HOME/.config/yakushi-control-deck"
STAMP="$(date +%Y%m%d-%H%M%S)"; BACKUP="$DATA/install-backups/$STAMP"
say(){ printf '%s\n' "$*"; }; fail(){ printf 'ERROR: %s\n' "$*" >&2; exit 1; }
command -v pacman >/dev/null 2>&1 || fail 'Arch Linux / pacman is required.'
command -v sudo >/dev/null 2>&1 || fail 'sudo is required.'
PACKAGES=(python python-gobject gtk4 gdk-pixbuf2 hyprland waybar rofi kitty fastfetch hyprpaper hyprlock pavucontrol playerctl brightnessctl wl-clipboard ttf-jetbrains-mono-nerd polkit)
missing=(); for package in "${PACKAGES[@]}"; do pacman -Qi "$package" >/dev/null 2>&1 || missing+=("$package"); done
if ((${#missing[@]})); then say 'Installing official Arch packages:'; printf '  %s\n' "${missing[@]}"; sudo pacman -S --needed "${missing[@]}"; fi

# Validate the release bundle before touching the user's desktop files.
[[ -x "$ROOT/smoke-test.sh" ]] || fail 'Package smoke-test helper is missing.'
"$ROOT/smoke-test.sh" --quiet || fail 'Package integrity check failed. Run ./smoke-test.sh for details.'
mkdir -p "$BACKUP" "$BIN" "$DATA"
backup_file(){ local src="$1" rel="$2"; [[ -e "$src" ]] || return 0; mkdir -p "$BACKUP/$(dirname "$rel")"; cp -a "$src" "$BACKUP/$rel"; }
backup_file "$HOME/.config/waybar/config.jsonc" waybar/config.jsonc; backup_file "$HOME/.config/waybar/style.css" waybar/style.css; backup_file "$HOME/.config/waybar/scripts" waybar/scripts
backup_file "$HOME/.config/rofi/config.rasi" rofi/config.rasi; backup_file "$HOME/.config/rofi/yakushi-opacity.rasi" rofi/yakushi-opacity.rasi; backup_file "$HOME/.config/rofi/scripts" rofi/scripts
backup_file "$HOME/.config/hypr/colors.css" hypr/colors.css; backup_file "$HOME/.config/hypr/colors.rasi" hypr/colors.rasi; backup_file "$HOME/.config/kitty/kitty.conf" kitty/kitty.conf; backup_file "$HOME/.config/kitty/yakushi-colors.conf" kitty/yakushi-colors.conf; backup_file "$HOME/.config/fastfetch/config.jsonc" fastfetch/config.jsonc; backup_file "$HOME/.config/fastfetch/logo.txt" fastfetch/logo.txt; backup_file "$HOME/.config/fastfetch/yakushi-logo.txt" fastfetch/yakushi-logo.txt
rm -rf "$TARGET"; mkdir -p "$TARGET" "$HOME/.config/waybar/scripts" "$HOME/.config/rofi/scripts" "$HOME/.config/hypr" "$HOME/.config/kitty" "$HOME/.config/fastfetch" "$HOME/.local/share/applications"
cp -a "$ROOT/yakushi_deck" "$TARGET/"; cp -a "$ROOT/integrations" "$TARGET/"; cp -a "$ROOT/tools" "$TARGET/"
[[ -d "$ROOT/screenshots" ]] && cp -a "$ROOT/screenshots" "$TARGET/"
cp -a "$ROOT/README.md" "$ROOT/LICENSE" "$ROOT/doctor.sh" "$ROOT/smoke-test.sh" "$ROOT/install-sddm-theme.sh" "$ROOT/bind-super-m-lock.fish" "$ROOT/restore-last-install.sh" "$ROOT/uninstall.sh" "$TARGET/"
cp -a "$ROOT/integrations/waybar/config.jsonc" "$HOME/.config/waybar/config.jsonc"; cp -a "$ROOT/integrations/waybar/style.css" "$HOME/.config/waybar/style.css"; cp -a "$ROOT/integrations/waybar/scripts/." "$HOME/.config/waybar/scripts/"
cp -a "$ROOT/integrations/rofi/config.rasi" "$HOME/.config/rofi/config.rasi"; cp -a "$ROOT/integrations/rofi/yakushi-opacity.rasi" "$HOME/.config/rofi/yakushi-opacity.rasi"; cp -a "$ROOT/integrations/rofi/scripts/." "$HOME/.config/rofi/scripts/"
cp -a "$ROOT/integrations/hypr/colors.css" "$HOME/.config/hypr/colors.css"; cp -a "$ROOT/integrations/hypr/colors.rasi" "$HOME/.config/hypr/colors.rasi"
chmod +x "$HOME/.config/waybar/scripts/"*.sh "$HOME/.config/rofi/scripts/"*.sh
if [[ ! -s "$HOME/.config/kitty/kitty.conf" ]]; then
  cat > "$HOME/.config/kitty/kitty.conf" <<'KITTY'
font_family JetBrainsMono Nerd Font
font_size 12.0
background_opacity 0.92
dynamic_background_opacity yes
window_padding_width 8

# YAKUSHI KITTY COLORS - KEEP THIS INCLUDE LAST
include yakushi-colors.conf
KITTY
  cat > "$HOME/.config/kitty/yakushi-colors.conf" <<'KITTYCOLORS'
# Generated by Yakushi Control Deck.
# YAKUSHI KITTY COLOR MODE: follow
background #0e0c0d
foreground #e8a29a
cursor #e8a29a
cursor_text_color #0e0c0d
selection_background #e8a29a
selection_foreground #171313
url_color #e8a29a
active_border_color #e8a29a
inactive_border_color #463f41
tab_bar_background #0e0c0d
active_tab_background #e8a29a
active_tab_foreground #171313
inactive_tab_background #242022
inactive_tab_foreground #e8a29a
color0 #0e0c0d
color1 #e8a29a
color2 #e8aca5
color3 #e8b5af
color4 #e8bdb8
color5 #e8b1aa
color6 #e8b9b3
color7 #e8a29a
color8 #584347
color9 #e8aaa3
color10 #e8b2ab
color11 #e8bab4
color12 #e8c2bd
color13 #e8b6b0
color14 #e8beb9
color15 #ecd0cc
KITTYCOLORS
fi

if [[ ! -s "$HOME/.config/fastfetch/config.jsonc" ]]; then
  cp -a "$ROOT/integrations/fastfetch/config.jsonc" "$HOME/.config/fastfetch/config.jsonc"
fi
if [[ ! -s "$HOME/.config/fastfetch/logo.txt" ]]; then
  cp -a "$ROOT/integrations/fastfetch/logo.txt" "$HOME/.config/fastfetch/logo.txt"
fi
if [[ ! -s "$HOME/.config/fastfetch/yakushi-logo.txt" ]]; then
  cp -a "$ROOT/integrations/fastfetch/yakushi-logo.txt" "$HOME/.config/fastfetch/yakushi-logo.txt"
fi
cat > "$BIN/yakushi-deck" <<LAUNCH
#!/usr/bin/env bash
cd "$TARGET"
exec python3 -m yakushi_deck "\$@"
LAUNCH
chmod +x "$BIN/yakushi-deck"
cat > "$HOME/.local/share/applications/yakushi-control-deck.desktop" <<DESKTOP
[Desktop Entry]
Name=Yakushi Control Deck
Comment=Lightweight Hyprland desktop control deck
Exec=$BIN/yakushi-deck
Type=Application
Categories=Settings;System;
Terminal=false
DESKTOP
python3 -m compileall -q "$TARGET/yakushi_deck"
python3 "$TARGET/tools/jsonc_check.py" "$HOME/.config/waybar/config.jsonc"
rofi -no-config -theme "$HOME/.config/rofi/config.rasi" -dump-theme >/dev/null
pkill -x waybar 2>/dev/null || true; nohup waybar >/tmp/yakushi-waybar.log 2>&1 &
printf '{"version":"1.2.12","backup":"%s","installed_at":"%s"}\n' "$BACKUP" "$STAMP" > "$DATA/install.json"
say ''; say '薬  Yakushi Control Deck 1.2.12 installed.'; say "Backup: $BACKUP"; say 'Left click 薬 -> Control Deck'; say 'Right click 薬 -> Rofi'; say 'Power button -> Rofi power menu'; say 'Run ./doctor.sh for diagnostics.'
