from __future__ import annotations

import os
import pwd
import re
import shlex
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path

from .history import record
from .io import atomic_write, load_json, run, save_json
from .paths import HYPRLOCK_CONFIG, LOCK_STATE, SDDM_PREVIEW, SDDM_STATE
from .theme import load as load_palette
from .typography import status as typography_status
from .wallpapers import current as current_wallpaper


@dataclass
class LockSettings:
    wallpaper: str = ""
    blur_passes: int = 3
    blur_size: int = 8
    brightness: float = 0.72
    clock_24h: bool = True
    show_date: bool = True


@dataclass
class SddmSettings:
    wallpaper: str = ""
    sync_palette: bool = True


def _merged(path: Path, defaults: dict) -> dict:
    value = load_json(path, defaults)
    merged = defaults.copy()
    merged.update(value)
    return merged


def lock_status() -> dict:
    data = _merged(LOCK_STATE, asdict(LockSettings()))
    if not data.get("wallpaper"):
        current = current_wallpaper()
        if current:
            data["wallpaper"] = str(current)
    data["available"] = shutil.which("hyprlock") is not None
    data["config"] = str(HYPRLOCK_CONFIG)
    return data


def sddm_status() -> dict:
    data = _merged(SDDM_STATE, asdict(SddmSettings()))
    if not data.get("wallpaper"):
        lock = lock_status()
        if lock.get("wallpaper"):
            data["wallpaper"] = str(lock["wallpaper"])
    data["available"] = shutil.which("sddm") is not None
    data["greeter"] = _greeter_binary() or ""
    theme_dir = Path("/usr/share/sddm/themes/yakushi")
    data["installed"] = (theme_dir / "Main.qml").is_file()
    data["active_theme"] = _active_sddm_theme()
    data["active"] = data["installed"] and data["active_theme"] == "yakushi"
    return data


def _hex_rgba(value: str, alpha: float = 1.0) -> str:
    value = (value or "#ffffff").strip().lstrip("#")
    if len(value) != 6 or not re.fullmatch(r"[0-9a-fA-F]{6}", value):
        value = "ffffff"
    r, g, b = (int(value[i:i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r}, {g}, {b}, {max(0.0, min(1.0, alpha)):.3f})"


def _font_family() -> str:
    info = typography_status()
    if info.get("enabled") and info.get("family"):
        return str(info["family"])
    return "serif"


def _resolve_wallpaper(value: str) -> Path | None:
    if value:
        path = Path(value).expanduser()
        if path.exists() and path.is_file():
            return path
    current = current_wallpaper()
    return current if current and current.exists() else None


def _hyprlock_config(settings: LockSettings) -> str:
    palette = load_palette()
    wallpaper = _resolve_wallpaper(settings.wallpaper)
    path_value = str(wallpaper) if wallpaper else ""
    time_value = "$TIME" if settings.clock_24h else "$TIME12"
    date_block = ""
    if settings.show_date:
        date_block = f"""
label {{
    monitor =
    text = cmd[update:60000] date +\"%A, %d %B\"
    color = {_hex_rgba(palette.muted)}
    font_size = 18
    font_family = {_font_family()}
    position = 0, 60
    halign = center
    valign = center
}}
"""

    return f"""# Generated by Yakushi Control Deck.
# Edit through Lock Screen Studio so backups and state stay in sync.

general {{
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}}

background {{
    monitor =
    path = {path_value}
    color = {_hex_rgba(palette.bg)}
    blur_passes = {int(settings.blur_passes)}
    blur_size = {int(settings.blur_size)}
    brightness = {float(settings.brightness):.2f}
    vibrancy = 0.15
    vibrancy_darkness = 0.05
}}

label {{
    monitor =
    text = {time_value}
    color = {_hex_rgba(palette.fg)}
    font_size = 86
    font_family = {_font_family()}
    position = 0, 150
    halign = center
    valign = center
}}
{date_block}
label {{
    monitor =
    text = $USER
    color = {_hex_rgba(palette.muted)}
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -38
    halign = center
    valign = center
}}

input-field {{
    monitor =
    size = 310, 54
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    outer_color = {_hex_rgba(palette.accent)}
    inner_color = {_hex_rgba(palette.surface, 0.88)}
    font_color = {_hex_rgba(palette.fg)}
    fail_color = rgba(220, 70, 80, 1.0)
    check_color = {_hex_rgba(palette.accent)}
    placeholder_text = <span foreground=\"##{palette.muted.lstrip('#')}\">Enter password</span>
    fail_text = <i>$FAIL</i>
    rounding = 14
    position = 0, -115
    halign = center
    valign = center
}}
"""


def apply_lock(settings: LockSettings) -> tuple[bool, str]:
    if shutil.which("hyprlock") is None:
        return False, "Hyprlock is not installed."
    wallpaper = _resolve_wallpaper(settings.wallpaper)
    if settings.wallpaper and wallpaper is None:
        return False, "The selected lock-screen wallpaper no longer exists."

    record("Lock screen", files=[p for p in (HYPRLOCK_CONFIG, LOCK_STATE) if p.exists()])
    atomic_write(HYPRLOCK_CONFIG, _hyprlock_config(settings))
    save_json(LOCK_STATE, asdict(settings))
    return True, "Lock screen updated. Use LOCK NOW to test it."


def refresh_lock_palette() -> tuple[bool, str]:
    """Regenerate only the palette-dependent Hyprlock config.

    Auto Color calls this after a successful theme change. It intentionally
    does not create a second history entry, so REVERT LAST still points at the
    palette change rather than an internal synchronization write.
    """
    if not HYPRLOCK_CONFIG.exists():
        return True, "Lock screen has not been generated yet."
    data = lock_status()
    settings = LockSettings(
        wallpaper=str(data.get("wallpaper", "")),
        blur_passes=int(data.get("blur_passes", 3)),
        blur_size=int(data.get("blur_size", 8)),
        brightness=float(data.get("brightness", 0.72)),
        clock_24h=bool(data.get("clock_24h", True)),
        show_date=bool(data.get("show_date", True)),
    )
    atomic_write(HYPRLOCK_CONFIG, _hyprlock_config(settings))
    return True, "Lock screen colors synchronized."


def lock_now() -> tuple[bool, str]:
    if shutil.which("hyprlock") is None:
        return False, "Hyprlock is not installed."
    proc = run(["sh", "-lc", "nohup hyprlock >/tmp/yakushi-hyprlock.log 2>&1 &"], timeout=2.0)
    return proc.returncode == 0, ("Lock screen launched." if proc.returncode == 0 else "Hyprlock could not be launched.")


def _package_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _sddm_template() -> Path:
    return _package_root() / "integrations" / "sddm" / "yakushi"


def _sddm_root_helper() -> Path:
    return Path(__file__).resolve().parent / "sddm_root.py"


def _greeter_binary() -> str | None:
    for candidate in ("sddm-greeter-qt6", "sddm-greeter"):
        path = shutil.which(candidate)
        if path:
            return path
    return None


def _active_sddm_theme() -> str:
    values: list[Path] = []
    for directory in (Path("/usr/lib/sddm/sddm.conf.d"), Path("/etc/sddm.conf.d")):
        if directory.exists():
            values.extend(sorted(directory.glob("*.conf")))
    if Path("/etc/sddm.conf").exists():
        values.append(Path("/etc/sddm.conf"))

    current = ""
    for path in values:
        try:
            text = path.read_text(errors="ignore")
        except Exception:
            continue
        block = re.search(r"(?ms)^\s*\[Theme\]\s*(.*?)(?=^\s*\[|\Z)", text)
        if not block:
            continue
        match = re.search(r"(?m)^\s*Current\s*=\s*(\S.*?)\s*$", block.group(1))
        if match:
            current = match.group(1).strip()
    return current


def _write_theme_user(directory: Path, wallpaper_name: str, *, preview_mode: bool = False) -> None:
    palette = load_palette()
    font = _font_family()
    lock = lock_status()
    blur_passes = max(0, int(lock.get("blur_passes", 3)))
    blur_size = max(1, int(lock.get("blur_size", 8)))
    # Hyprlock and Qt Quick use different blur units. This maps the lock-screen
    # controls into a stable 0..1 SDDM strength while keeping the same intent.
    blur_strength = min(0.90, (blur_passes / 8.0) * 0.55 + (blur_size / 20.0) * 0.35)
    brightness = max(0.25, min(1.0, float(lock.get("brightness", 0.72))))
    dim_opacity = max(0.08, min(0.70, 1.0 - brightness))
    try:
        default_user = pwd.getpwuid(os.getuid()).pw_name
    except Exception:
        default_user = os.environ.get("USER", "")
    text = f"""[General]
background={wallpaper_name}
accent={palette.accent}
backgroundColor={palette.bg}
surface={palette.surface}
surfaceAlt={palette.surface_alt}
foreground={palette.fg}
muted={palette.muted}
border={palette.border}
font={font}
clock24={'true' if bool(lock.get('clock_24h', True)) else 'false'}
showDate={'true' if bool(lock.get('show_date', True)) else 'false'}
blurStrength={blur_strength:.2f}
dimOpacity={dim_opacity:.2f}
defaultUser={default_user}
previewMode={'true' if preview_mode else 'false'}
"""
    (directory / "theme.conf.user").write_text(text)


def stage_sddm(settings: SddmSettings, *, preview_mode: bool = False) -> tuple[bool, str, Path | None]:
    template = _sddm_template()
    if not template.exists():
        return False, "Yakushi SDDM theme template is missing.", None

    if SDDM_PREVIEW.exists():
        shutil.rmtree(SDDM_PREVIEW)
    shutil.copytree(template, SDDM_PREVIEW)

    wallpaper = _resolve_wallpaper(settings.wallpaper)
    if not settings.wallpaper:
        lock = lock_status()
        lock_wallpaper = lock.get("wallpaper", "")
        if lock_wallpaper:
            candidate = Path(str(lock_wallpaper)).expanduser()
            if candidate.exists() and candidate.is_file():
                wallpaper = candidate
    wallpaper_name = ""
    if wallpaper:
        wallpaper_name = f"background{wallpaper.suffix.lower()}"
        shutil.copy2(wallpaper, SDDM_PREVIEW / wallpaper_name)
    _write_theme_user(SDDM_PREVIEW, wallpaper_name, preview_mode=preview_mode)
    return True, "SDDM preview prepared.", SDDM_PREVIEW


def preview_sddm(settings: SddmSettings) -> tuple[bool, str]:
    greeter = _greeter_binary()
    if not greeter:
        return False, "SDDM greeter preview binary was not found."
    ok, message, directory = stage_sddm(settings, preview_mode=True)
    if not ok or directory is None:
        return False, message
    proc = run([
        "sh", "-lc",
        f'env -u QML2_IMPORT_PATH -u QML_IMPORT_PATH -u QT_PLUGIN_PATH '
        f'nohup "{greeter}" --test-mode --theme "{directory}" '
        f'>/tmp/yakushi-sddm-preview.log 2>&1 &'
    ], timeout=2.0)
    return proc.returncode == 0, ("SDDM preview launched." if proc.returncode == 0 else "SDDM preview could not be launched.")


def _verify_sddm_install() -> tuple[bool, str]:
    theme_main = Path("/usr/share/sddm/themes/yakushi/Main.qml")
    active = _active_sddm_theme()
    if theme_main.is_file() and active == "yakushi":
        return True, "Yakushi SDDM installed and verified. It will appear at the next login/reboot."
    details = []
    if not theme_main.is_file():
        details.append("theme files were not installed")
    if active != "yakushi":
        details.append(f"active theme is {active or 'default'}")
    return False, "SDDM install verification failed: " + "; ".join(details) + "."


def _launch_sddm_sudo_installer(helper: Path, directory: Path) -> bool:
    terminal = shutil.which("kitty")
    if not terminal or shutil.which("sudo") is None:
        return False
    command = (
        f"sudo /usr/bin/python3 {shlex.quote(str(helper))} install --source {shlex.quote(str(directory))}; "
        "status=$?; echo; "
        "if [ $status -eq 0 ]; then "
        "echo 'Yakushi SDDM installed. Log out or reboot to see it.'; "
        "else echo 'Yakushi SDDM installation failed.'; fi; "
        "echo; read -r -p 'Press Enter to close...' _; exit $status"
    )
    proc = run([terminal, "--title", "Yakushi SDDM Installer", "sh", "-lc", command], timeout=2.0)
    return proc.returncode == 0


def install_sddm(settings: SddmSettings) -> tuple[bool, str]:
    if shutil.which("sddm") is None:
        return False, "SDDM is not installed on this system."

    ok, message, directory = stage_sddm(settings)
    if not ok or directory is None:
        return False, message

    helper = _sddm_root_helper()
    if not helper.exists():
        return False, "SDDM privilege helper is missing."

    # Preserve the user's selected login wallpaper/settings even when the
    # privilege path falls back to a terminal sudo prompt.
    save_json(SDDM_STATE, asdict(settings))

    if shutil.which("pkexec") is not None:
        proc = run(["pkexec", "/usr/bin/python3", str(helper), "install", "--source", str(directory)], timeout=120.0)
        if proc.returncode == 0:
            return _verify_sddm_install()

    # Some Polkit setups reject pkexec authentication even though normal sudo
    # works. Open a visible terminal prompt instead of silently leaving users
    # on the stock SDDM theme.
    if _launch_sddm_sudo_installer(helper, directory):
        return True, "Polkit could not complete the install, so Yakushi opened a sudo installer terminal. Enter your Linux password there, then log out or reboot."

    return False, "SDDM needs administrator access. Run ./install-sddm-theme.sh from the Yakushi repository."


def _launch_sddm_sudo_disable(helper: Path) -> bool:
    terminal = shutil.which("kitty")
    if not terminal or shutil.which("sudo") is None:
        return False
    command = (
        f"sudo /usr/bin/python3 {shlex.quote(str(helper))} disable; "
        "status=$?; echo; "
        "if [ $status -eq 0 ]; then "
        "echo 'Yakushi SDDM disabled. Log out or reboot when convenient.'; "
        "else echo 'Yakushi SDDM restore failed.'; fi; "
        "echo; read -r -p 'Press Enter to close...' _; exit $status"
    )
    proc = run([terminal, "--title", "Yakushi SDDM Restore", "sh", "-lc", command], timeout=2.0)
    return proc.returncode == 0


def disable_sddm() -> tuple[bool, str]:
    helper = _sddm_root_helper()
    if not helper.exists():
        return False, "SDDM privilege helper is missing."

    if shutil.which("pkexec") is not None:
        proc = run(["pkexec", "/usr/bin/python3", str(helper), "disable"], timeout=120.0)
        if proc.returncode == 0:
            return True, "Yakushi SDDM disabled. Your previous SDDM configuration was restored."

    if _launch_sddm_sudo_disable(helper):
        return True, "Polkit could not complete the restore, so Yakushi opened a sudo restore terminal."

    return False, "SDDM restore needs administrator access."
